### ISSUE TITLE
[Preparation] Define healthy code development process

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#1]
* Prepare prettier config
  * prettier file
  * prettier check on CI
* prepare .gitignore
* prepare Readme:
  * naming convention
  * licensing
    * CI check for licensing
  * CI Link check
* prepare github tags
* add test coverage metrics

**Comment by crystalin** [comment]
@librelois @timbrinded 
This ticket is to track all the setup we need to do for the repo in order to maintain it easily over time. Feel free to edit and add your thoughts

**Comment by timbrinded** [comment]
think done now
