### ISSUE TITLE
Add a way to run common code before each suite

### ISSUE THREAD

**Issue by tmpolaczyk** [Moonsong-Labs/moonwall#193]
We have a `dev_tanssi` environment where every `.ts` file has some code in the `beforeAll` section. Since this code is common across all the files, we could deduplicate it if there was a way to run the same code before every beforeAll. So maybe moonwall could allow an optional `dev_tanssi/index.ts` file, to define the common code there. In the future this feature could be expanded to allow some kind of runtime configuration, for cases where modifying the moonwall.config.json file is not flexible enough.

**Comment by timbrinded** [comment]
if you want to execute something before the network launches, you can run a script, if you want something before a suite you have beforeAll. I dont think there's logical headroom for any other DRY optimizations here given that each suite is its own test context.

In terms of reducing boilerplate though you can always write project specific helpers.

**Comment by tmpolaczyk** [comment]
At the time I wrote the issue our `beforeAll` was pretty big, but now thanks to the latest moonwall updates it is only:

```
        beforeAll(() => {
            alice = context.keyring.alice;
            bob = context.keyring.bob;
            charlie = context.keyring.charlie;

            polkadotJs = context.polkadotJs();
        });
```

So copy-pasting that doesn't look that ugly.
