### ISSUE TITLE
Support running dev tests without compiling

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#225]
In order to open Moonbeam test suite to third parties desiring to include their own test, it would be easier if they could run the dev tests without having to compile local moonbeam first. Wether through downloading the binary manually or by specifying to download the binary as an option (like --moonbeam-binary 0.32.1)

**Comment by timbrinded** [comment]
They can already do this with `moonwall download moonbeam latest` or via the menu options. We have multi repo support now (with tansii), i should be able to extend it to arbitrary GH repos via the moonwall config if that would suffice @crystalin
