### ISSUE TITLE
Add "repeat" option to menu

### ISSUE THREAD

**Issue by notlesh** [Moonsong-Labs/moonwall#244]
After running some command, it would be awesome if the following menu had an option to "repeat" the last thing. E.g.:

```
 HTML  Report is generated
       You can run npx vite preview --outDir html to see the test results.
? Environment : dev_moonbase
Please select a choice:  (Use arrow keys)
  Tail:      Print the logs of the current running node to this console 
 ...
  Repeat:    Repeat the last command <bonus: print command here>
```

**Comment by notlesh** [comment]
I wonder if this could help speed things up, too...

**Comment by timbrinded** [comment]
@notlesh We already remember the last command you did and the last thing you grepped, so you just need to press return twice to repeat a test:
![grep](https://github.com/Moonsong-Labs/moonwall/assets/79199034/199b6c3a-aebe-42db-b421-0d79ef90631c)


Is this sufficient to fulfill your feat req?

**Comment by notlesh** [comment]
Oh, I think that would do it. I have a (maybe bad?) habit of hitting `up + <Enter>`, which does the wrong thing here.

This works for me, thanks for pointing it out!
