### ISSUE TITLE
Wrong log file name

### ISSUE THREAD

**Issue by tmpolaczyk** [Moonsong-Labs/moonwall#249]
When running some tanssi tests:

```
pnpm moonwall run chopsticks_dancebox_upgrade CANT
```

I see this message on top of the screen:

```
  🌐  Node db has started, listening on ports - Websocket: 8000
  🪵   Log location: /home/tomasz/projects/tanssi/test/tmp/node_logs/node_node_undefined_150995.log
  🖥️   https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A8000
```

The log folder is correct, but the log file is wrong, that's a file that exists but it is not written to by this test, it keeps its old contents. A different log file is created and written to, it's easy to find because it is the most recent one, but I wonder why this log location is wrong.

```
pnpm moonwall --version
```

returns "unknown" but I'm on 4.0.20

**Comment by timbrinded** [comment]
this should be fixed now
