### ISSUE TITLE
Allow running scripts before "run" command, similar to runScripts option for tests

### ISSUE THREAD

**Issue by tmpolaczyk** [Moonsong-Labs/moonwall#258]
In tanssi we use runScripts to generate chainspec files before running zombienet tests, like this in moonwall.config.json:

```
            "runScripts": ["build-spec.sh", "download-polkadot.sh"],
```

That works when running `pnpm moonwall test zombie_tanssi`, but the scripts are not being run when running `pnpm moonwall run zombie_tanssi`.

The scripts should run when using the `run` command as well.

**Comment by timbrinded** [comment]
Done now, should work as before. Plus now there's a manual command to execute them from the main menu
