### ISSUE TITLE
Support contract deployment retry 

### ISSUE THREAD

**Issue by noandrea** [Moonsong-Labs/moonwall#265]
In the moonbeam CI there are sometimes test failures that are usually resolved by re-running the tests. 
One specific case is deploying a contract in the test setup  (e.g. [here](https://github.com/moonbeam-foundation/moonbeam/blob/07371bdc14c50f58a22cba2ce1c032bd5e7a2d99/test/suites/dev/test-precompile/test-precompile-assets-erc20-low-level.ts#L51) )

A possible way to alleviate this problem could be the possibility to specify in the `deployCreateCompiledContract` a parameter for a number of retries, that is default to 1.

**Comment by timbrinded** [comment]
I would be reluctant to support a feature that makes it permissible to have flaky and non-deterministic tests.

Regarding the specific issue you linked, that is very irksome and troubling to hear. I do wonder if there's some underlying race-condition which is going on. I think I may have to turn off multi-threading to resolve issues like this.

**Comment by noandrea** [comment]
Thanks @timbrinded , in this particular instance, the problem was that the node was slow to start, so oftentimes the tests will time out during set-up. Closing this for now.
