### ISSUE TITLE
testFileDir should use exact path

### ISSUE THREAD

**Issue by tmpolaczyk** [Moonsong-Labs/moonwall#267]
Given the following suites defined in moonwall.config.json:

```
{
            "name": "zombie_tanssi",
            "testFileDir": ["suites/para"],
},{
            "name": "zombie_tanssi_rotation",
            "testFileDir": ["suites/para-rotation"],
},
```

I expected `pnpm moonwall run zombie_tanssi` to only run the first suite. It does run the first suite, but including the files from the other suite as well. I guess it's because `suites/para` is turned into `suites/para*` and that also matches the directory of the other suite `suites/para-rotation`. The test files from `suites/para-rotation` run first, and then the test fails with this error message:

```
⎯⎯⎯⎯⎯⎯ Unexpected Exit ⎯⎯⎯⎯⎯⎯⎯
Error: process.exit called with "1"
 ❯ Object.<anonymous> ../node_modules/.pnpm/@zombienet+orchestrator@0.0.50_@polkadot+util@12.4.2_@types+node@20.5.6/node_modules/@zombienet/orchestrator/dist/orchestrator.js:328:21
 ❯ fulfilled ../node_modules/.pnpm/@zombienet+orchestrator@0.0.50_@polkadot+util@12.4.2_@types+node@20.5.6/node_modules/@zombienet/orchestrator/dist/orchestrator.js:5:58
```

Not sure what happens, maybe a timeout, or zombienet crashes because it is running 2 suites. It would be nice to have a better error message there.

I also tried using `"testFileDir": ["suites/para/"],`, but that resulted in the same as `"testFileDir": ["suites/para"],`.

The solution should be making sure that `suites/para` does not match `suites/para-rotation`, and it would be nice to improve the error message for "Unexpected Exit".

**Comment by timbrinded** [comment]
Raised upstream:
https://github.com/vitest-dev/vitest/issues/4425

**Comment by timbrinded** [comment]
Fixed in latest
