### ISSUE TITLE
Have the ability to set default timeout per test suite

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#269]
Currently it is defined in the config file but at the root part which I think is made to be for all the test suite.

**Comment by timbrinded** [comment]
Vitest does not allow for timeouts in test suites :unamused: only hooks and tests.

This is due to their design of how they create and schedule tasks (tests are a core primitive, whereas suites are just thin wrappers).

**Comment by crystalin** [comment]
But the timeout in the config files is applied to all the test when you run the test suites no ?

**Comment by crystalin** [comment]
Otherwise can we add an option `--timeout` to the "test" command ? 
Cause I don't see why the timeout for "dev" and for "zombienet" should be the same

**Comment by timbrinded** [comment]
good point. i can certainly add an environment specific timeout to the moonwall config which overrides the defaultTestTimeout (which applies to the runner).

**Comment by crystalin** [comment]
Ok, it is not that important, but I wanted to ensure dev test don't wait 2 or 5 minutes to fail, as it makes troubleshooting quite slow

**Comment by timbrinded** [comment]
This has been done for a while now
