### ISSUE TITLE
Concurrent execution is breaking with the --wasmtime-precompiled=wasm

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#272]
For some reason, some tests are timing out (500000ms) when executing the dev_moonbase test with the `--wasmtime-precompiled=wasm`. It seems as if moonwall is not detecting the node has started and waits for it 500s.

This doesn't happen when running with multithread off

**Comment by timbrinded** [comment]
Fixed in latest version (4.2.X) when switching over to vitest@beta with better thread handling.
