### ISSUE TITLE
getEthers returns WebSocketProvider;

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#28]
getEthers should return the EtherJs or we should use a different name for the provider.
The provider is useful because it allows to use directly `send(method, [params])` but etherjs is also nice to use

**Comment by timbrinded** [comment]
Unlike web3, there isn't an ethers API - they separate it into `provider` and `signer`.

A signer is just a provider enriched with a signing key, which is now what you get when calling: `context.ethersSigner`

If you want access to the underlying provider, it is `context.ethersSigner.provider`. The rest of the Ethers function library can be imported from moonwall-cli now.

E.g. 

```
import {
  describeSuite,
  expect,
  beforeAll,
  Signer,
  ethers,
  MoonwallContext,
} from "@moonsong-labs/moonwall-cli";
```

**Comment by timbrinded** [comment]
added in https://github.com/Moonsong-Labs/moonwall/commit/e27c8e8a53ee2095d5609ff2bdec1f31517a8950
