### ISSUE TITLE
Adds pnpm watch script to build when file is changed 

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#29]
This is useful when using pnpm link to work with test in a repo and adding feature to moonwall

**Comment by crystalin** [comment]
I don't see the package watch script in the package.json :(

**Comment by timbrinded** [comment]
https://github.com/Moonsong-Labs/moonwall/blob/795604e620a5e3a9d0c06ca973674700623969d9/packages/cli/package.json#L45

It's in the corresponding `package.json` for each package (cli / util). When doing it at the monorepo level it seems to mess up with tsup (our bundler)
