### ISSUE TITLE
Chopsticks 0.9.4 buildBlockMode input fails

### ISSUE THREAD

**Issue by Chralt98** [Moonsong-Labs/moonwall#340]
You correctly specify [this](https://github.com/Moonsong-Labs/moonwall/blob/edf4476fb3885be59fa5434cd7bac2a78f5192df/packages/types/config_schema.json#L20-L28) chopsticks setting.

But you use a number input [here](https://github.com/Moonsong-Labs/moonwall/blob/edf4476fb3885be59fa5434cd7bac2a78f5192df/packages/cli/src/internal/commandParsers.ts#L82-L84). Chopsticks version 0.9.4 expects an option `Instant`, `Manual`, `Batch` instead.

**Comment by timbrinded** [comment]
Thanks, this has been fixed in latest version
