### ISSUE TITLE
Provider name should be included in `context.upgradeRuntime(context)`

### ISSUE THREAD

**Issue by Chralt98** [Moonsong-Labs/moonwall#342]
I have the following scenario (from [here](https://github.com/zeitgeistpm/zeitgeist/blob/b2725443881abec5cf82b2bcb1e5cc3674d25130/integration-tests/tests/rt-upgrade-chopsticks/test-chopsticks-runtime-upgrade.ts#L21-L39)):

```typescript
            zeitgeistParaApi = context.polkadotJs("ZeitgeistPara");
            relayApi = context.polkadotJs("PolkadotRelay");
            hydradxParaApi = context.polkadotJs("HydraDXPara");

            const paraZeitgeistNetwork = zeitgeistParaApi.consts.system.version.specName.toString();
            expect(paraZeitgeistNetwork, "Para API incorrect").to.contain("zeitgeist");

            const relayNetwork = relayApi.consts.system.version.specName.toString();
            expect(relayNetwork, "Relay API incorrect").to.contain("polkadot");

            const paraHydraDXNetwork = hydradxParaApi.consts.system.version.specName.toString();
            expect(paraHydraDXNetwork, "Para API incorrect").to.contain("hydradx");

            const rtBefore = zeitgeistParaApi.consts.system.version.specVersion.toNumber();
            log(`About to upgrade to runtime at:`);
            log(MoonwallContext.getContext().rtUpgradePath);

            await context.upgradeRuntime(context);
```

I figured out that the first endpoint port number(8000 is before 8001 and 8002) inside the moonwall config [here](https://github.com/zeitgeistpm/zeitgeist/blob/b2725443881abec5cf82b2bcb1e5cc3674d25130/integration-tests/moonwall.config.json#L114) determines the chain to upgrade using `await context.upgradeRuntime(context);`. I would have expected to be able to specify the provider name just like with `createBlock` [here](https://github.com/zeitgeistpm/zeitgeist/blob/b2725443881abec5cf82b2bcb1e5cc3674d25130/integration-tests/tests/rt-upgrade-chopsticks/test-chopsticks-runtime-upgrade.ts#L51).

**Comment by timbrinded** [comment]
Implemented
