### ISSUE TITLE
Custom download name not working

### ISSUE THREAD

**Issue by themacexpert** [Moonsong-Labs/moonwall#370]
When using a command like
`pnpm moonwall download moonbeam v0.35.0 --overwrite --output-name MyRenamedMoonbeamClient
`

The client is downloaded with its regular name of moonbeam and the custom name is not used. There are no errors produced, just doesn't receive the custom name. I'm on Mac

**Comment by themacexpert** [comment]
I also notice that it doesn't seem to create about my overwrite instructions 
`pnpm moonwall download moonbeam v0.34.0 --overwrite false`
and will overwrite the file regardless

**Comment by timbrinded** [comment]
I don't know where those options are from, but they arent valid for moonwall. Sadly the help menu seems to be broken, but it should be:

`pnpm moonwall download <binaryName> <version> <outputFolder>`

If you want to call it something other than the binary name, you have to do that via the normal means.

Also it's always overwrite.
