### ISSUE TITLE
Node keep running after moonwall crashes

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#43]
I'm not sure it is intended or not, but when moonwall exists (crashes in my case), the nodes are still running in the background.
This can be an issue as re-running the tests will connect to the old node and not the new ones

**Comment by timbrinded** [comment]
Not intended, have had this before and ive fixed most the scenarios but either reintroduced it with zombienet changes or missed new cases.

Do you have any rough repro steps? is this a true crash (out of mem, seg fault, process exit 1 etc ) or just a vitest caught error?

**Comment by timbrinded** [comment]
Fixed in latest
