### ISSUE TITLE
Some logs appear with zombienet without meaning

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#44]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/329248/229342157-d5f4876f-f144-4c03-839d-77f403c0eab8.png">

**Comment by timbrinded** [comment]
Raised upstream at: https://github.com/paritytech/zombienet/issues/885

**Comment by timbrinded** [comment]
Fixed in latest
