### ISSUE TITLE
Support to display log instantly

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#49]
Moonwall should support display logs instantly without having to go back to the menu, something like
`hotkey: [v] increase test verbosity - [n] display node logs - [s] silence all logs`

which could be applied when a test is running

**Comment by timbrinded** [comment]
this is partially completed by saving logs in the background to your local machine: cwd + `/tmp/node_logs`

**Comment by crystalin** [comment]
it means now you need 2 windows to use it, it also means you need to rely on time to sync them.
